---
version: '2'

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    network_mode: "host"
    volumes:
      - ./create_indexes.js:/docker-entrypoint-initdb.d/create_indexes.js:ro
      - /vol4/mongo-data:/data/db
