---
version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    network_mode: "host"
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - /vol1/zk-data:/var/lib/zookeeper/data
      - /vol2/zk-txn-logs:/var/lib/zookeeper/log

  broker:
    image: confluentinc/cp-kafka:7.2.0
    network_mode: "host"
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'st133vm109.rtb-lab.pl:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://st133vm109.rtb-lab.pl:9092,PLAINTEXT_HOST://st133vm109.rtb-lab.pl:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MINUTES: 15
      KAFKA_LOG_CLEANUP_POLICY: delete
    volumes:
      - /vol3/kafka-data:/var/lib/kafka/data

  init-kafka:
    image: confluentinc/cp-kafka:7.2.0
    network_mode: "host"
    depends_on:
      - broker
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server st133vm109.rtb-lab.pl:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server st133vm109.rtb-lab.pl:9092 --create --if-not-exists --topic user-tags --replication-factor 1 --partitions 1
      kafka-configs --bootstrap-server st133vm109.rtb-lab.pl:9092  --entity-type topics --entity-name user-tags --alter --add-config retention.ms=900000

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server st133vm109.rtb-lab.pl:9092 --list
      "
